name: Release Gem

on:
  push:
    branches: ["main"]
    paths: ["lib/**/version.rb"]

jobs:
  release:
    if: github.repository == 'cr7pt0gr4ph7/jekyll-gem-resolver'
    name: "Release Gem (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        ruby_version: ["3.0"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Build and Publish Gem
        uses: rubygems/release-gem@v1
        with:
          await-release: false
